version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.3
jobs:
  build:
    docker:
      - image: 'circleci/python:3.6'
    steps:
      - checkout
      - run: mkdir bucket && echo "lorum ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          from: bucket
          to: 's3://aws-snipets/masterone'
          region: AWS_REGION_DEFAULT
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
      - aws-s3/copy:
          from: bucket/build_asset.txt
          to: 's3://aws-snipets'
          region: AWS_REGION_DEFAULT
          arguments: '--dryrun'